#spring.application.name=journal App
#spring.data.mongodb.uri=mongodb+srv://root:Samarenter%4012@samar.eos2q4v.mongodb.net/?retryWrites=true&w=majority&appName=Samar
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
